# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.5
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: amousavig@icloud.com
author_name: Ali Mousavi
preset_name: starter
project_name: moth-frontend

